console.log('Car active')

let Cars = [
    {
      "id" : "1",
      "ten" : "718 Boxster",
      "hinhanh" : "../database/Image/718-boxster.png",
      "congxuat" : 350,
      "tocdo" : 275,
      "tangtoc" : 4.7,
      "cao" : 1285,
      "dai" : 4895,
      "giatieuchuan" : 3960,
    },
    {
      "id" : "2",
      "ten" : "911 Carrera S",
      "hinhanh" : "../database/Image/911-carrera-s.png",
      "congxuat" : 375,
      "tocdo" : 300,
      "tangtoc" : 3.7,
      "cao" : 1295,
      "dai" : 4950,
      "giatieuchuan" : 8530
    },
    {
      "id" : "3",
      "ten" : "911 Carrera",
      "hinhanh" : "../database/Image/911-carrera.png",
      "congxuat" : 425,
      "tocdo" : 325,
      "tangtoc" : 4.2,
      "cao" : 1305,
      "dai" : 4756,
      "giatieuchuan" : 7620
    },
    {
      "id" : "4",
      "ten" : "911 Targa 4",
      "hinhanh" : "../database/Image/911-targa-4.png",
      "congxuat" : 450,
      "tocdo" : 350,
      "tangtoc" : 4.4,
      "cao" : 1305,
      "dai" : 4950,
      "giatieuchuan" : 8910
    },
    {
      "id" : "5",
      "ten" : "911 Turbo",
      "hinhanh" : "../database/Image/911-turbo.png",
      "congxuat" : 500,
      "tocdo" : 350,
      "tangtoc" : 2.8,
      "cao" : 1285,
      "dai" : 4756,
      "giatieuchuan" : 14250
    },
    {
      "id" : "6",
      "ten" : "Cayenne",
      "hinhanh" : "../database/Image/cayenne.png",
      "congxuat" : 500,
      "tocdo" : 275,
      "tangtoc" : 6.0,
      "cao" : 1295,
      "dai" : 4895,
      "giatieuchuan" : 5560
    },
    {
      "id" : "7",
      "ten" : "Taycan 4 Cross Turismo",
      "hinhanh" : "../database/Image/taycan-4-cross-turismo.png",
      "congxuat" : 375,
      "tocdo" : 300,
      "tangtoc" : 5.1,
      "cao" : 1305,
      "dai" : 4950,
      "giatieuchuan" : 4880
    },
    {
      "id" : "8",
      "ten" : "Macan",
      "hinhanh" : "../database/Image/macan.png",
      "congxuat" : 500,
      "tocdo" : 350,
      "tangtoc" : 6.4,
      "cao" : 1305,
      "dai" : 4895,
      "giatieuchuan" : 3350
    },
    {
      "id" : "9",
      "ten" : "Panamera",
      "hinhanh" : "../database/Image/panamera.png",
      "congxuat" : 350,
      "tocdo" : 270,
      "tangtoc" : 5.6,
      "cao" : 1285,
      "dai" : 4756,
      "giatieuchuan" : 5560
    },
    {
      "id" : "10",
      "ten" : "Taycan",
      "hinhanh" : "../database/Image/taycan.png",
      "congxuat" : 375,
      "tocdo" : 300,
      "tangtoc" : 5.4,
      "cao" : 1295,
      "dai" : 4950,
      "giatieuchuan" : 4260
    },
    {
      "id" : "11",
      "ten" : "Taycan 4S",
      "hinhanh" : "../database/Image/taycan-4s.png",
      "congxuat" : 450,
      "tocdo" : 325,
      "tangtoc" : 4.0,
      "cao" : 1305,
      "dai" : 4895,
      "giatieuchuan" : 5140
    },
    {
      "id" : "12",
      "ten" : "Taycan GTS",
      "hinhanh" : "../database/Image/taycan-gts.png",
      "congxuat" : 425,
      "tocdo" : 275,
      "tangtoc" : 3.7,
      "cao" : 1305,
      "dai" : 4895,
      "giatieuchuan" : 6160
    },
    {
      "id" : "13",
      "ten" : "Taycan Turbo",
      "hinhanh" : "../database/Image/taycan-turbo.png",
      "congxuat" : 375,
      "tocdo" : 325,
      "tangtoc" : 3.2,
      "cao" : 1295,
      "dai" : 4950,
      "giatieuchuan" : 7130
    },
    {
      "id" : "14",
      "ten" : "Taycan Turbo S",
      "hinhanh" : "../database/Image/taycan-turbo-s.png",
      "congxuat" : 375,
      "tocdo" : 300,
      "tangtoc" : 2.8,
      "cao" : 1285,
      "dai" : 4756,
      "giatieuchuan" : 8500
    },
    {
      "id" : "15",
      "ten" : "Panamera Platinum Edition",
      "hinhanh" : "../database/Image/panamera-platinum-edition.png",
      "congxuat" : 500,
      "tocdo" : 350,
      "tangtoc" : 5.6,
      "cao" : 1295,
      "dai" : 4895,
      "giatieuchuan" : 6030
    },
    {
      "id" : "16",
      "ten" : "Panamera 4",
      "hinhanh" : "../database/Image/panamera-4.png",
      "congxuat" : 500,
      "tocdo" : 325,
      "tangtoc" : 5.3,
      "cao" : 1305,
      "dai" : 4895,
      "giatieuchuan" : 5700
    },
    {
      "id" : "17",
      "ten" : "Panamera 4 Platinum Edition",
      "hinhanh" : "../database/Image/panamera-4-platinum-edition.png",
      "congxuat" : 350,
      "tocdo" : 325,
      "tangtoc" : 5.3,
      "cao" : 1305,
      "dai" : 4950,
      "giatieuchuan" : 6210
    },
    {
      "id" : "18",
      "ten" : "Macan T",
      "hinhanh" : "../database/Image/macan-t.png",
      "congxuat" : 375,
      "tocdo" : 300,
      "tangtoc" : 6.4,
      "cao" : 1285,
      "dai" : 4895,
      "giatieuchuan" : 3570
    },
    {
      "id" : "19",
      "ten" : "Macan S",
      "hinhanh" : "../database/Image/macan-s.png",
      "congxuat" : 425,
      "tocdo" : 300,
      "tangtoc" : 4.8,
      "cao" : 1295,
      "dai" : 4895,
      "giatieuchuan" : 4400
    },
    {
      "id" : "20",
      "ten" : "Macan GTS",
      "hinhanh" : "../database/Image/macan-gts.png",
      "congxuat" : 450,
      "tocdo" : 350,
      "tangtoc" : 4.5,
      "cao" : 1305,
      "dai" : 4756,
      "giatieuchuan" : 5340
    },
    {
      "id" : "21",
      "ten" : "Taycan 4S Cross Turismo",
      "hinhanh" : "../database/Image/taycan-4s-cross-turismo.png",
      "congxuat" : 375,
      "tocdo" : 325,
      "tangtoc" : 4.1,
      "cao" : 1295,
      "dai" : 4950,
      "giatieuchuan" : 5350
    },
    {
      "id" : "22",
      "ten" : "Taycan Turbo Cross Turismo",
      "hinhanh" : "../database/Image/taycan-turbo-cross-turismo.png",
      "congxuat" : 350,
      "tocdo" : 325,
      "tangtoc" : 3.3,
      "cao" : 1305,
      "dai" : 4950,
      "giatieuchuan" : 7190
    },
    {
      "id" : "23",
      "ten" : "Cayenne Coupe",
      "hinhanh" : "../database/Image/cayenne-coupe.png",
      "congxuat" : 500,
      "tocdo" : 300,
      "tangtoc" : 5.7,
      "cao" : 1305,
      "dai" : 4895,
      "giatieuchuan" : 5810
    },
    {
      "id" : "24",
      "ten" : "Cayenne S",
      "hinhanh" : "../database/Image/cayenne-s.png",
      "congxuat" : 375,
      "tocdo" : 275,
      "tangtoc" : 5.0,
      "cao" : 1295,
      "dai" : 4950,
      "giatieuchuan" : 7770
    },
    {
      "id" : "25",
      "ten" : "Cayenne S Coupe",
      "hinhanh" : "../database/Image/cayenne-s-coupe.png",
      "congxuat" : 375,
      "tocdo" : 300,
      "tangtoc" : 4.7,
      "cao" : 1295,
      "dai" : 4756,
      "giatieuchuan" : 8070
    },
    {
      "id" : "26",
      "ten" : "Cayenne Turbo GT",
      "hinhanh" : "../database/Image/cayenne-turbo-gt.png",
      "congxuat" : 350,
      "tocdo" : 300,
      "tangtoc" : 3.3,
      "cao" : 1305,
      "dai" : 4895,
      "giatieuchuan" : 14360
    },
    {
      "id" : "27",
      "ten" : "911 Turbo Cabriolet",
      "hinhanh" : "../database/Image/911-turbo-cabriolet.png",
      "congxuat" : 425,
      "tocdo" : 350,
      "tangtoc" : 2.9,
      "cao" : 1285,
      "dai" : 4895,
      "giatieuchuan" : 15070
    },
    {
      "id" : "28",
      "ten" : "911 Turbo S",
      "hinhanh" : "../database/Image/911-turbo-s.png",
      "congxuat" : 425,
      "tocdo" : 325,
      "tangtoc" : 2.7,
      "cao" : 1295,
      "dai" : 4950,
      "giatieuchuan" : 16500
    },
    {
      "id" : "29",
      "ten" : "911 Turbo S Cabriolet",
      "hinhanh" : "../database/Image/911-turbo-s-cabriolet.png",
      "congxuat" : 450,
      "tocdo" : 350,
      "tangtoc" : 2.8,
      "cao" : 1305,
      "dai" : 4756,
      "giatieuchuan" : 17380
    },
    {
      "id" : "30",
      "ten" : "911 Targa 4S",
      "hinhanh" : "../database/Image/911-targa-4s.png",
      "congxuat" : 375,
      "tocdo" : 275,
      "tangtoc" : 3.8,
      "cao" : 1305,
      "dai" : 4950,
      "giatieuchuan" : 9850
    },
    {
      "id" : "31",
      "ten" : "911 Targa 4 GTS",
      "hinhanh" : "../database/Image/911-targa-4-gts.png",
      "congxuat" : 500,
      "tocdo" : 325,
      "tangtoc" : 3.5,
      "cao" : 1295,
      "dai" : 4895,
      "giatieuchuan" : 11000
    },
    {
      "id" : "32",
      "ten" : "911 Carrera T",
      "hinhanh" : "../database/Image/911-carrera-t.png",
      "congxuat" : 375,
      "tocdo" : 350,
      "tangtoc" : 4.0,
      "cao" : 1305,
      "dai" : 4950,
      "giatieuchuan" : 8310
    },
    {
      "id" : "33",
      "ten" : "911 Carrera Cabriolet",
      "hinhanh" : "../database/Image/911-carrera-cabriolet.png",
      "congxuat" : 350,
      "tocdo" : 300,
      "tangtoc" : 4.4,
      "cao" : 1295,
      "dai" : 4895,
      "giatieuchuan" : 8470
    },
    {
      "id" : "34",
      "ten" : "911 Carrera GTS",
      "hinhanh" : "../database/Image/911-carrera-gts.png",
      "congxuat" : 480,
      "tocdo" : 275,
      "tangtoc" : 3.2,
      "cao" : 1285,
      "dai" : 4756,
      "giatieuchuan" : 9630
    },
    {
      "id" : "35",
      "ten" : "911 Carrera GTS Cabriolet",
      "hinhanh" : "../database/Image/911-carrera-gts-cabriolet.png",
      "congxuat" : 480,
      "tocdo" : 325,
      "tangtoc" : 3.6,
      "cao" : 1285,
      "dai" : 4895,
      "giatieuchuan" : 10510
    },
    {
      "id" : "36",
      "ten" : "911 Carrera 4",
      "hinhanh" : "../database/Image/911-carrera-4.png",
      "congxuat" : 450,
      "tocdo" : 300,
      "tangtoc" : 4.2,
      "cao" : 1305,
      "dai" : 4950,
      "giatieuchuan" : 8100
    },
    {
      "id" : "37",
      "ten" : "911 Carrera 4 Cabriolet",
      "hinhanh" : "../database/Image/911-carrera-4-cabriolet.png",
      "congxuat" : 450,
      "tocdo" : 275,
      "tangtoc" : 4.4,
      "cao" : 1305,
      "dai" : 4895,
      "giatieuchuan" : 8910
    },
    {
      "id" : "38",
      "ten" : "911 Carrera 4 GTS",
      "hinhanh" : "../database/Image/911-carrera-4-gts.png",
      "congxuat" : 350,
      "tocdo" : 350,
      "tangtoc" : 3.3,
      "cao" : 1285,
      "dai" : 4950,
      "giatieuchuan" : 10120
    },
    {
      "id" : "39",
      "ten" : "911 Carrera 4 GTS Cabriolet",
      "hinhanh" : "../database/Image/911-carrera-4-gts-cabriolet.png",
      "congxuat" : 350,
      "tocdo" : 275,
      "tangtoc" : 3.5,
      "cao" : 1295,
      "dai" : 4756,
      "giatieuchuan" : 11000
    },
    {
      "id" : "40",
      "ten" : "911 Carrera S Cabriolet",
      "hinhanh" : "../database/Image/911-carrera-s-cabriolet.png",
      "congxuat" : 375,
      "tocdo" : 325,
      "tangtoc" : 3.9,
      "cao" : 1295,
      "dai" : 4895,
      "giatieuchuan" : 9350
    },
    {
      "id" : "41",
      "ten" : "911 Carrera 4S",
      "hinhanh" : "../database/Image/911-carrera-4s.png",
      "congxuat" : 450,
      "tocdo" : 325,
      "tangtoc" : 3.6,
      "cao" : 1285,
      "dai" : 4950,
      "giatieuchuan" : 8980
    },
    {
      "id" : "42",
      "ten" : "911 Carrera 4S Cabriolet",
      "hinhanh" : "../database/Image/911-carrera-4s-cabriolet.png",
      "congxuat" : 450,
      "tocdo" : 325,
      "tangtoc" : 3.8,
      "cao" : 1305,
      "dai" : 4950,
      "giatieuchuan" : 9850
    },
    {
      "id" : "43",
      "ten" : "718 Cayman Style Edition",
      "hinhanh" : "../database/Image/718-cayman-style-edition.png",
      "congxuat" : 425,
      "tocdo" : 275,
      "tangtoc" : 4.9,
      "cao" : 1295,
      "dai" : 4756,
      "giatieuchuan" : 4260
    },
    {
      "id" : "44",
      "ten" : "718 Cayman T",
      "hinhanh" : "../database/Image/718-cayman-t.png",
      "congxuat" : 500,
      "tocdo" : 275,
      "tangtoc" : 4.9,
      "cao" : 1305,
      "dai" : 4756,
      "giatieuchuan" : 4090
    },
    {
      "id" : "45",
      "ten" : "718 Cayman S",
      "hinhanh" : "../database/Image/718-cayman-s.png",
      "congxuat" : 350,
      "tocdo" : 275,
      "tangtoc" : 4.4,
      "cao" : 1285,
      "dai" : 4895,
      "giatieuchuan" : 4770
    },
    {
      "id" : "46",
      "ten" : "718 Boxster Style Edition",
      "hinhanh" : "../database/Image/718-boxster-style-edition.png",
      "congxuat" : 500,
      "tocdo" : 275,
      "tangtoc" : 4.9,
      "cao" : 1305,
      "dai" : 4950,
      "giatieuchuan" : 4380
    },
    {
      "id" : "47",
      "ten" : "718 Boxster T",
      "hinhanh" : "../database/Image/718-boxster-t.png",
      "congxuat" : 425,
      "tocdo" : 275,
      "tangtoc" : 4.9,
      "cao" : 1295,
      "dai" : 4756,
      "giatieuchuan" : 4210
    },
    {
      "id" : "48",
      "ten" : "718 Boxster S",
      "hinhanh" : "../database/Image/718-boxster-s.png",
      "congxuat" : 350,
      "tocdo" : 300,
      "tangtoc" : 4.4,
      "cao" : 1285,
      "dai" : 4950,
      "giatieuchuan" : 4880
    },
  ]